# Generated by Django 5.2.8 on 2026-02-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'student')},
        ),
    ]
