# Generated by Django 5.2.8 on 2026-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='conversion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_conversion',
            field=models.BooleanField(default=False, help_text='Track if this internship converted to a full-time job'),
        ),
    ]
