# Generated by Django 5.2.8 on 2026-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Full-time Job')], default='internship', max_length=20)),
                ('stipend', models.CharField(help_text='e.g. $1000/mo or Equity', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('HIRED', 'Hired')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
