# Generated by Django 5.2.8 on 2026-02-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('education', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=50)),
            ],
        ),
    ]
