# Generated by Django 6.0.2 on 2026-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='actively_looking',
            field=models.BooleanField(default=True, help_text='Whether the student is actively looking for jobs (controls resume push to companies)'),
        ),
    ]
