# Generated by Django 6.0.2 on 2026-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_actively_looking'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('graduated', 'Graduated')], default='1', help_text='Current academic standing', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_roles',
            field=models.CharField(blank=True, default='', help_text='Target roles (e.g. Backend Engineer, Product Designer)', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='start_date',
            field=models.DateField(blank=True, help_text='Earliest available start date', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_hours',
            field=models.PositiveIntegerField(default=20, help_text='Hours available per week'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', help_text='Work setting preference', max_length=20),
        ),
    ]
