# Generated by Django 6.0.2 on 2026-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_status',
            field=models.CharField(choices=[('student', 'Student'), ('fresher', 'Fresher / Unemployed'), ('switcher', 'Career Switcher'), ('skilled', 'Skilled Worker (Non-degree)')], default='student', help_text='Current professional status', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience_level',
            field=models.CharField(choices=[('1', '1st Year (Student)'), ('2', '2nd Year (Student)'), ('3', '3rd Year (Student)'), ('4', 'Final Year (Student)'), ('grad', 'Graduated'), ('entry', 'Entry Level (<1 yr)'), ('mid', 'Mid Level (1-3 yrs)'), ('senior', 'Senior (3+ yrs)')], default='1', help_text='Academic year or professional experience level', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio / Github / Social Link', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='availability',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible')], default='full_time', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education',
            field=models.CharField(blank=True, help_text='University/Degree (Optional for non-students)', max_length=255),
        ),
    ]
