# Generated by Django 6.0.2 on 2026-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentprofile_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', 'Final Year')], help_text='Current academic year (Students only)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_experience',
            field=models.CharField(blank=True, choices=[('0', 'Fresher / <1 Year'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], help_text='Professional experience (Non-students)', max_length=20, null=True),
        ),
    ]
