# Generated by Django 6.0.2 on 2026-02-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_studentprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience_level',
            field=models.CharField(choices=[('student_1', '1st Year'), ('student_2', '2nd Year'), ('student_3', '3rd Year'), ('student_final', 'Final Year'), ('entry', 'Entry Level (<1 year)'), ('mid', 'Mid Level (1-3 years)'), ('senior', 'Senior (3-5 years)'), ('expert', 'Expert (5+ years)')], default='student_1', help_text='Academic year or professional experience level', max_length=20),
        ),
    ]
