# Generated by Django 5.2.8 on 2026-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder_collab', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderneed',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technical Support'), ('HIRING', 'Hiring Advice'), ('FUNDING', 'Funding/Pitching'), ('PARTNER', 'Partnership'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
